// Concrete PROV elements: `ProvEntity`, `ProvActivity`, `ProvAgent`.
//
// Port of `ProvElement` + the element classes (model.py:613, :663, :778, :999).
// The fluent builder helpers (`e.wasGeneratedBy(...)`, `a.used(...)`, etc.)
// delegate to the bundle's authoring API, which is M4 — they are deferred. What
// lands here is the class shape: `static prov_type` / `FORMAL_ATTRIBUTES`, the
// element identifier requirement, and `ProvActivity`'s time accessors.

import { DateTime } from "luxon";

import {
  ProvRecord,
  type RecordBundle,
  type ProvAttributes,
} from "./record";
import type {
  ProvBundle,
  EntityRef,
  ActivityRef,
  AgentRef,
} from "../bundle";
import type { QualifiedName } from "../identifier";
import { type AttrValue } from "../value";
import type { DateLike } from "../datetime";
import { ProvElementIdentifierRequired } from "../error";
import { registerRecordClass } from "./registry";
import {
  PROV_ENTITY,
  PROV_ACTIVITY,
  PROV_AGENT,
  PROV_ATTR_STARTTIME,
  PROV_ATTR_ENDTIME,
} from "../constants";

/** Base class for PROV elements (nodes). Every element requires an identifier (`model.py:613`). */
export abstract class ProvElement extends ProvRecord {
  /**
   * @param bundle     The owning bundle.
   * @param identifier The element identifier — required.
   * @param attributes Optional initial attributes.
   * @throws {ProvElementIdentifierRequired} If `identifier` is `null` (`model.py:622`).
   */
  constructor(
    bundle: RecordBundle,
    identifier: QualifiedName | null,
    attributes?: ProvAttributes,
  ) {
    if (identifier === null) {
      throw new ProvElementIdentifierRequired();
    }
    super(bundle, identifier, attributes);
  }

  override isElement(): boolean {
    return true;
  }
}

/** A PROV Entity (`model.py:663`). The fluent methods assert relations *from* this entity. */
export class ProvEntity extends ProvElement {
  static override readonly prov_type = PROV_ENTITY;

  /** This entity was generated by `activity` (`model.py:670`). Returns `this`. */
  wasGeneratedBy(
    activity?: ActivityRef,
    time?: DateLike,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasGeneratedBy(
      this,
      activity,
      time,
      undefined,
      attributes,
    );
    return this;
  }

  /** This entity was invalidated by `activity` (`model.py:690`). Returns `this`. */
  wasInvalidatedBy(
    activity?: ActivityRef,
    time?: DateLike,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasInvalidatedBy(
      this,
      activity,
      time,
      undefined,
      attributes,
    );
    return this;
  }

  /** This entity was derived from `usedEntity` (`model.py:710`). Returns `this`. */
  wasDerivedFrom(
    usedEntity: EntityRef,
    activity?: ActivityRef,
    generation?: EntityRef,
    usage?: EntityRef,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasDerivedFrom(
      this,
      usedEntity,
      activity,
      generation,
      usage,
      undefined,
      attributes,
    );
    return this;
  }

  /** This entity was attributed to `agent` (`model.py:736`). Returns `this`. */
  wasAttributedTo(agent: AgentRef, attributes?: ProvAttributes): this {
    (this._bundle as ProvBundle).wasAttributedTo(
      this,
      agent,
      undefined,
      attributes,
    );
    return this;
  }

  /** This entity is an alternate of `alternate2` (`model.py:750`). Returns `this`. */
  alternateOf(alternate2: EntityRef): this {
    (this._bundle as ProvBundle).alternateOf(this, alternate2);
    return this;
  }

  /** This entity is a specialization of `generalEntity` (`model.py:759`). Returns `this`. */
  specializationOf(generalEntity: EntityRef): this {
    (this._bundle as ProvBundle).specializationOf(this, generalEntity);
    return this;
  }

  /** This (collection) entity had `entity` as a member (`model.py:768`). Returns `this`. */
  hadMember(entity: EntityRef): this {
    (this._bundle as ProvBundle).hadMember(this, entity);
    return this;
  }
}

/** A PROV Activity, carrying optional start/end times (`model.py:778`). */
export class ProvActivity extends ProvElement {
  static override readonly prov_type = PROV_ACTIVITY;
  static override readonly FORMAL_ATTRIBUTES = [
    PROV_ATTR_STARTTIME,
    PROV_ATTR_ENDTIME,
  ] as const;

  /**
   * Sets the activity's start and/or end time. Mirrors `set_time`
   * (`model.py:786`): the value is stored **raw** (bypassing `addAttributes`
   * coercion) and **replaces** any existing value. Preserving this quirk keeps a
   * naive ISO string byte-identical on output instead of acquiring a luxon offset
   * (DEVIATIONS — `set_time` raw-store).
   *
   * @param startTime The start time (string kept verbatim; `Date` → `DateTime`).
   * @param endTime   The end time (same handling).
   */
  setTime(
    startTime?: DateLike | null,
    endTime?: DateLike | null,
  ): void {
    if (startTime !== undefined && startTime !== null) {
      this.attrs.set(PROV_ATTR_STARTTIME, rawTime(startTime));
    }
    if (endTime !== undefined && endTime !== null) {
      this.attrs.set(PROV_ATTR_ENDTIME, rawTime(endTime));
    }
  }

  /** The activity's start time, as stored (`model.py:806`). */
  getStartTime(): AttrValue | undefined {
    return this.attrs.first(PROV_ATTR_STARTTIME);
  }

  /** The activity's end time, as stored (`model.py:815`). */
  getEndTime(): AttrValue | undefined {
    return this.attrs.first(PROV_ATTR_ENDTIME);
  }

  /** This activity used `entity` (`model.py:826`). Returns `this`. */
  used(entity: EntityRef, time?: DateLike, attributes?: ProvAttributes): this {
    (this._bundle as ProvBundle).used(
      this,
      entity,
      time,
      undefined,
      attributes,
    );
    return this;
  }

  /** This activity was informed by `informant` (`model.py:846`). Returns `this`. */
  wasInformedBy(informant: ActivityRef, attributes?: ProvAttributes): this {
    (this._bundle as ProvBundle).wasInformedBy(
      this,
      informant,
      undefined,
      attributes,
    );
    return this;
  }

  /** This activity was started by `trigger` (`model.py:859`). Returns `this`. */
  wasStartedBy(
    trigger?: EntityRef,
    starter?: ActivityRef,
    time?: DateLike,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasStartedBy(
      this,
      trigger,
      starter,
      time,
      undefined,
      attributes,
    );
    return this;
  }

  /** This activity was ended by `trigger` (`model.py:883`). Returns `this`. */
  wasEndedBy(
    trigger?: EntityRef,
    ender?: ActivityRef,
    time?: DateLike,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasEndedBy(
      this,
      trigger,
      ender,
      time,
      undefined,
      attributes,
    );
    return this;
  }

  /** This activity was associated with `agent` (`model.py:905`). Returns `this`. */
  wasAssociatedWith(
    agent?: AgentRef,
    plan?: EntityRef,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).wasAssociatedWith(
      this,
      agent,
      plan,
      undefined,
      attributes,
    );
    return this;
  }
}

/** A PROV Agent (`model.py:999`). */
export class ProvAgent extends ProvElement {
  static override readonly prov_type = PROV_AGENT;

  /** This agent acted on behalf of `responsible` (`model.py:1006`). Returns `this`. */
  actedOnBehalfOf(
    responsible: AgentRef,
    activity?: ActivityRef,
    attributes?: ProvAttributes,
  ): this {
    (this._bundle as ProvBundle).actedOnBehalfOf(
      this,
      responsible,
      activity,
      undefined,
      attributes,
    );
    return this;
  }
}

/** Coerces a {@link DateLike} for raw time storage: strings/DateTimes kept; `Date` → `DateTime`. */
function rawTime(time: DateLike): AttrValue {
  return time instanceof Date ? DateTime.fromJSDate(time) : time;
}

// Self-registration (model.py:1101). Loading this module populates the registry.
registerRecordClass(PROV_ENTITY, ProvEntity);
registerRecordClass(PROV_ACTIVITY, ProvActivity);
registerRecordClass(PROV_AGENT, ProvAgent);
